# Generated by Django 5.2.5 on 2025-09-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_productreturnitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
