# Generated by Django 5.2.5 on 2025-09-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_salestransaction_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='refund_method',
            field=models.CharField(choices=[('Credit', 'Credit to Account'), ('Cash', 'Cash Refund')], max_length=10),
        ),
    ]
